-- Disable foreign key checks temporarily
SET FOREIGN_KEY_CHECKS = 0;

-- Truncate tables in order of dependencies
TRUNCATE TABLE BATCH_STEP_EXECUTION_CONTEXT;
TRUNCATE TABLE BATCH_JOB_EXECUTION_CONTEXT;
TRUNCATE TABLE BATCH_STEP_EXECUTION;
TRUNCATE TABLE BATCH_JOB_EXECUTION_PARAMS;
TRUNCATE TABLE BATCH_JOB_EXECUTION;
TRUNCATE TABLE BATCH_JOB_INSTANCE;

-- Reset the sequences
ALTER TABLE BATCH_JOB_EXECUTION_SEQ ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE BATCH_JOB_SEQ ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE BATCH_STEP_EXECUTION_SEQ ALTER COLUMN ID RESTART WITH 1;

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;